author: Eero Vilpponen
description: 
main: me.eerovil.betterpeaceful.BetterPeaceful
name: BetterPeaceful
load: POSTWORLD
version: 1.0.0
api-version: '1.20'
website: 
dev-url: 
permissions:
    betterpeaceful.use:
        description: A description.
        default: op
commands:
    betterpeaceful:
        aliases: [alias1,alias2]
        description: A description.
        usage: /<command> [arg0] [arg1]
        permission: betterpeaceful.use
        permission-message: You don't have the permission <permission> to use this command
